services:
  postgres:
    image: postgres:18
    container_name: Fils-rouge-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbGestSport
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend

  app:
     image: wdorian/sporthive-app-26:latest
     container_name: Fils-rouge-app
     ports:
       - "8080:8080"
     networks:
       - backend



volumes:
  postgres_data:

networks:
  backend:
